CREATE TABLE CHANGE_RISK_FUNCTION (
  ID               BIGSERIAL PRIMARY KEY,
  PROFILE_ID       BIGINT REFERENCES QUALITY_PROFILE (ID),
  METRICIDENTIFIER VARCHAR(50) NOT NULL
);

CREATE TABLE RISK_CHARGE (
  ID               BIGSERIAL PRIMARY KEY,
  RISK_FUNCTION_ID BIGINT REFERENCES CHANGE_RISK_FUNCTION (ID),
  AMOUNT           DOUBLE PRECISION NOT NULL,
  OPERATOR         VARCHAR(2)       NOT NULL,
  THRESHOLD        BIGINT           NOT NULL
);
