ALTER TABLE QUALITY_VIOLATION DROP COLUMN VIOLATION_ID CASCADE;
ALTER TABLE QUALITY_VIOLATION ADD COLUMN ARTEFACT_ID BIGINT NOT NULL;
ALTER TABLE QUALITY_VIOLATION ADD CONSTRAINT ARTEFACT_FK FOREIGN KEY (ARTEFACT_ID) REFERENCES ARTEFACT (ID);
