CREATE TABLE PROJECT (
  ID             BIGSERIAL PRIMARY KEY,
  NAME           TEXT         NOT NULL,
  CRONEXPRESSION VARCHAR(100) NOT NULL,
  SONAR_URL      TEXT         NOT NULL,
  SONAR_PROJECT  TEXT         NOT NULL,
  SONAR_USERNAME TEXT,
  SONAR_PASSWORD TEXT,
  SCM_TYPE       INT          NOT NULL,
  SCM_URL        TEXT         NOT NULL,
  SCM_USERNAME   TEXT,
  SCM_PASSWORD   TEXT
);

ALTER TABLE QUALITY_ANALYSIS ADD COLUMN PROJECT_ID BIGINT NOT NULL;
ALTER TABLE QUALITY_ANALYSIS ADD CONSTRAINT PROJECT_FK FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID);
ALTER TABLE QUALITY_ANALYSIS DROP COLUMN PROFILE_ID CASCADE;
